// <auto-generated />
namespace AMM_Domain_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _02_02_20191 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_02_20191));
        
        string IMigrationMetadata.Id
        {
            get { return "201902020933123_02_02_2019-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
