// <auto-generated />
namespace AMM_Domain_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _01_02_20192 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_02_20192));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011903105_01_02_2019-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
