//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMM_Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMMContainer : DbContext
    {
        public AMMContainer()
            : base("name=AMMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Transaction> TransactionSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Family> FamilySet { get; set; }
        public virtual DbSet<Source> SourceSet { get; set; }
        public virtual DbSet<TypeOfSource> TypeOfSourceSet { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogSet { get; set; }
    }
}
