//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMM_Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Money { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserId1 { get; set; }
    
        public virtual TypeOfSource Type { get; set; }
    }
}
